# Lint.yml
name: Lint
on: [push, pull_request]

jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftFormat
        run: swiftformat --lint . --strict --reporter github-actions-log
